#include <xlpp/sidecar.hpp>

#include <miniz.h>

#include <cstdlib>
#include <cstring>
#include <memory>
#include <stdexcept>

namespace xlpp {
namespace {

// ---------------------------------------------------------------------------
// Minimal, targeted XML scanning. workbook.xml is machine-generated by Excel;
// we only need <sheets>/<sheet>, <definedNames>/<definedName>, and <calcPr>.
// Elements in the corpus are unprefixed (default spreadsheetml namespace).
// ---------------------------------------------------------------------------

std::string xml_unescape(const std::string &in) {
    std::string out;
    out.reserve(in.size());
    for (std::size_t i = 0; i < in.size(); ++i) {
        if (in[i] != '&') {
            out += in[i];
            continue;
        }
        auto end = in.find(';', i);
        if (end == std::string::npos) {
            throw std::runtime_error("xml_unescape: unterminated entity");
        }
        auto entity = in.substr(i + 1, end - i - 1);
        if (entity == "amp") {
            out += '&';
        } else if (entity == "lt") {
            out += '<';
        } else if (entity == "gt") {
            out += '>';
        } else if (entity == "quot") {
            out += '"';
        } else if (entity == "apos") {
            out += '\'';
        } else if (!entity.empty() && entity[0] == '#') {
            auto code = entity[1] == 'x' || entity[1] == 'X'
                ? std::strtoul(entity.c_str() + 2, nullptr, 16)
                : std::strtoul(entity.c_str() + 1, nullptr, 10);
            if (code == 0 || code > 0x10FFFF) {
                throw std::runtime_error("xml_unescape: bad char reference &" + entity + ";");
            }
            // UTF-8 encode.
            if (code < 0x80) {
                out += static_cast<char>(code);
            } else if (code < 0x800) {
                out += static_cast<char>(0xC0 | (code >> 6));
                out += static_cast<char>(0x80 | (code & 0x3F));
            } else if (code < 0x10000) {
                out += static_cast<char>(0xE0 | (code >> 12));
                out += static_cast<char>(0x80 | ((code >> 6) & 0x3F));
                out += static_cast<char>(0x80 | (code & 0x3F));
            } else {
                out += static_cast<char>(0xF0 | (code >> 18));
                out += static_cast<char>(0x80 | ((code >> 12) & 0x3F));
                out += static_cast<char>(0x80 | ((code >> 6) & 0x3F));
                out += static_cast<char>(0x80 | (code & 0x3F));
            }
        } else {
            throw std::runtime_error("xml_unescape: unknown entity &" + entity + ";");
        }
        i = end;
    }
    return out;
}

// One parsed start tag: attributes plus positions for iterating content.
struct Tag {
    std::size_t start = std::string::npos;      // position of '<'
    std::size_t content_begin = 0;              // just past '>'
    bool self_closing = false;
    std::vector<std::pair<std::string, std::string>> attrs;

    const std::string *attr(const std::string &key) const {
        for (const auto &kv : attrs) {
            if (kv.first == key) {
                return &kv.second;
            }
        }
        return nullptr;
    }
};

// Finds the next <name ...> start tag at/after `from`. Exact element name
// match (not a prefix of a longer name). Returns tag with npos start if none.
Tag find_tag(const std::string &xml, const std::string &name, std::size_t from) {
    Tag tag;
    const std::string open = "<" + name;
    auto pos = from;
    while (true) {
        pos = xml.find(open, pos);
        if (pos == std::string::npos) {
            return tag;
        }
        char next = pos + open.size() < xml.size() ? xml[pos + open.size()] : '\0';
        if (next == ' ' || next == '>' || next == '/' || next == '\t' || next == '\n') {
            break;
        }
        pos += open.size();
    }
    tag.start = pos;
    auto i = pos + open.size();
    // Parse attributes until '>' or '/>'.
    while (i < xml.size()) {
        while (i < xml.size() && (xml[i] == ' ' || xml[i] == '\t' || xml[i] == '\n' ||
                                  xml[i] == '\r')) {
            ++i;
        }
        if (i >= xml.size()) {
            throw std::runtime_error("find_tag: unterminated <" + name + ">");
        }
        if (xml[i] == '>') {
            tag.content_begin = i + 1;
            return tag;
        }
        if (xml[i] == '/') {
            tag.self_closing = true;
            tag.content_begin = xml.find('>', i);
            if (tag.content_begin == std::string::npos) {
                throw std::runtime_error("find_tag: unterminated <" + name + "/>");
            }
            ++tag.content_begin;
            return tag;
        }
        auto eq = xml.find('=', i);
        if (eq == std::string::npos) {
            throw std::runtime_error("find_tag: malformed attribute in <" + name + ">");
        }
        auto key = xml.substr(i, eq - i);
        auto quote = xml[eq + 1];
        if (quote != '"' && quote != '\'') {
            throw std::runtime_error("find_tag: unquoted attribute in <" + name + ">");
        }
        auto val_end = xml.find(quote, eq + 2);
        if (val_end == std::string::npos) {
            throw std::runtime_error("find_tag: unterminated attribute in <" + name + ">");
        }
        tag.attrs.emplace_back(key, xml_unescape(xml.substr(eq + 2, val_end - eq - 2)));
        i = val_end + 1;
    }
    throw std::runtime_error("find_tag: unterminated <" + name + ">");
}

std::string element_text(const std::string &xml, const Tag &tag, const std::string &name) {
    if (tag.self_closing) {
        return {};
    }
    const std::string close = "</" + name + ">";
    auto end = xml.find(close, tag.content_begin);
    if (end == std::string::npos) {
        throw std::runtime_error("element_text: missing " + close);
    }
    return xml_unescape(xml.substr(tag.content_begin, end - tag.content_begin));
}

std::string read_zip_entry(const std::string &xlsx_path, const char *entry) {
    mz_zip_archive zip;
    std::memset(&zip, 0, sizeof(zip));
    if (!mz_zip_reader_init_file(&zip, xlsx_path.c_str(), 0)) {
        throw std::runtime_error("sidecar: cannot open zip: " + xlsx_path);
    }
    std::size_t size = 0;
    void *data = mz_zip_reader_extract_file_to_heap(&zip, entry, &size, 0);
    if (data == nullptr) {
        mz_zip_reader_end(&zip);
        throw std::runtime_error("sidecar: missing " + std::string(entry) + " in " + xlsx_path);
    }
    std::string content(static_cast<const char *>(data), size);
    mz_free(data);
    mz_zip_reader_end(&zip);
    return content;
}

} // namespace

WorkbookSidecar load_workbook_sidecar(const std::string &xlsx_path) {
    const auto xml = read_zip_entry(xlsx_path, "xl/workbook.xml");
    WorkbookSidecar sidecar;

    // <sheets><sheet name="..." .../>...</sheets> — order defines localSheetId.
    auto sheets = find_tag(xml, "sheets", 0);
    if (sheets.start == std::string::npos) {
        throw std::runtime_error("sidecar: no <sheets> in " + xlsx_path);
    }
    auto sheets_end = xml.find("</sheets>", sheets.start);
    for (auto pos = sheets.content_begin;;) {
        auto sheet = find_tag(xml, "sheet", pos);
        if (sheet.start == std::string::npos || sheet.start > sheets_end) {
            break;
        }
        auto name = sheet.attr("name");
        if (name == nullptr) {
            throw std::runtime_error("sidecar: <sheet> without name in " + xlsx_path);
        }
        sidecar.sheet_names.push_back(*name);
        pos = sheet.content_begin;
    }
    if (sidecar.sheet_names.empty()) {
        throw std::runtime_error("sidecar: zero sheets in " + xlsx_path);
    }

    // <definedNames> is optional.
    auto dns = find_tag(xml, "definedNames", 0);
    if (dns.start != std::string::npos && !dns.self_closing) {
        auto dns_end = xml.find("</definedNames>", dns.start);
        for (auto pos = dns.content_begin;;) {
            auto dn = find_tag(xml, "definedName", pos);
            if (dn.start == std::string::npos || dn.start > dns_end) {
                break;
            }
            DefinedName parsed;
            auto name = dn.attr("name");
            if (name == nullptr) {
                throw std::runtime_error("sidecar: <definedName> without name in " + xlsx_path);
            }
            parsed.name = *name;
            if (auto sheet_id = dn.attr("localSheetId")) {
                parsed.local_sheet_id = std::strtoul(sheet_id->c_str(), nullptr, 10);
                if (*parsed.local_sheet_id >= sidecar.sheet_names.size()) {
                    throw std::runtime_error("sidecar: localSheetId out of range for '" +
                                             parsed.name + "' in " + xlsx_path);
                }
            }
            if (auto hidden = dn.attr("hidden")) {
                parsed.hidden = *hidden == "1" || *hidden == "true";
            }
            parsed.value = element_text(xml, dn, "definedName");
            sidecar.defined_names.push_back(std::move(parsed));
            pos = dn.content_begin;
        }
    }

    // <calcPr> is optional; attributes override Excel defaults.
    auto calc = find_tag(xml, "calcPr", 0);
    if (calc.start != std::string::npos) {
        if (auto iterate = calc.attr("iterate")) {
            sidecar.calc.iterate = *iterate == "1" || *iterate == "true";
        }
        if (auto count = calc.attr("iterateCount")) {
            sidecar.calc.iterate_count = std::strtoul(count->c_str(), nullptr, 10);
        }
        if (auto delta = calc.attr("iterateDelta")) {
            sidecar.calc.iterate_delta = std::strtod(delta->c_str(), nullptr);
        }
    }

    return sidecar;
}

} // namespace xlpp
